// Icônes du site : celles qui ont une version animée par parties (animated.tsx) remplacent leur équivalent Phosphor,
// toutes les autres restent Phosphor. Importer d'ici, jamais directement de "@phosphor-icons/react".
export * from "@phosphor-icons/react/ssr";
export type { IconProps } from "@phosphor-icons/react";
export {
  ArrowLeft,
  Bell,
  Broadcast,
  Camera,
  CaretDown,
  CaretUpDown,
  ChartBar,
  ChartLineUp,
  ChatsCircle,
  Check,
  ClockCounterClockwise,
  DotsThree,
  Eye,
  Faders,
  FilmSlate,
  FilmStrip,
  Flag,
  Gauge,
  Gear,
  GitMerge,
  Globe,
  Headphones,
  Key,
  Lifebuoy,
  LinkSimple,
  List,
  Lock,
  LockKey,
  LockOpen,
  MagnifyingGlass,
  MapTrifold,
  Microphone,
  PaperPlaneTilt,
  PlugsConnected,
  Question,
  Radio,
  Record,
  Record as RecordIcon,
  Robot,
  Rows,
  ShareNetwork,
  ShieldCheck,
  ShieldWarning,
  SignOut,
  SlidersHorizontal,
  SpeakerSimpleHigh,
  SpeakerSimpleSlash,
  SquaresFour,
  Stop,
  Tag,
  Trash,
  UserCircle,
  Users,
  UsersThree,
  VideoCamera,
  WifiLow,
  X,
} from "./animated";
